### ISSUE TITLE
feature/4_MPE_Admin_Home_Page

### ISSUE THREAD

**Issue by mesc03** [DanielBucayan/PBL_TEST#7]
I recently created a new html file which is admin_home.html and I am partially done with my work. If there are any comments or ideas, let me know! Thank you! It is still a work in progress and comment to me your thoughts on it.

**Comment by DanielBucayan** [comment]
The Admin Home Page is working properly. Although, proper access control is to be added next time. This would do for the initial prototype. Thanks!
